### ISSUE TITLE
Eclemma Eclipse Plugin NullPointerException

### ISSUE THREAD

**Issue by ghost** [jacoco/eclemma#26]
i am getting the following exception after execute my junit test.
After exception is thrown my application terminated  without junit or console error and Junit view shows all test as passed.

Thanks

eclemma version: 2.2.0.201210261515

Session Data:

```
eclipse.buildId=M20120208-0800
java.version=1.7.0_09
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=tr_GB
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product org.eclipse.epp.package.java.product -consoleLog
```

Exception Track Trace:

```
java.lang.NullPointerException
    at com.mountainminds.eclemma.internal.ui.coverageview.CoverageView$4.paint(CoverageView.java:188)
    at org.eclipse.jface.viewers.OwnerDrawLabelProvider$OwnerDrawListener.handleEvent(OwnerDrawLabelProvider.java:59)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1077)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1062)
    at org.eclipse.swt.widgets.Tree.CDDS_ITEMPOSTPAINT(Tree.java:853)
    at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7375)
    at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5534)
    at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1896)
    at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5086)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4584)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4985)
    at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
    at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2425)
    at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1533)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4623)
    at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5937)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4972)
    at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
    at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2531)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3752)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
```

**Comment by Godin** [comment]
@marchof I'm going to close this one as outdated in presence of commit 18a5b28c2480e0e326f9d8a3e40c520c94d0350b and absence of feedback, objections?

**Comment by marchof** [comment]
@Godin Let's close this. Hopefully we get more details through Eclipse Error Reporting soon. Then we will track this on Bugzilla anyways.

**Comment by iachelini** [comment]
No further objection from my side, except that commit 18a5b28 <https://github.com/jacoco/eclemma/commit/18a5b28c2480e0e326f9d8a3e40c520c94d0350b>  didn’t contain a JUnit test. :) 
It was in the paint-method, therefore excused, I guess.

**Comment by Godin** [comment]
We are progressively adding tests for UI code in our new home at Eclipse Foundation - https://github.com/eclipse/eclemma
