### ISSUE TITLE
Setting the interrupted status of a thread in a unit test causes "Error while dumping coverage data (code 5013)."

### ISSUE THREAD

**Issue by AndreasBrieg** [jacoco/eclemma#64]
I was unit testing some code in Kepler that needed to restore the interrupted status of the current thread after catching an `InterruptedException`.

When I ran the coverage using EclEmma I received the error 
> Error while dumping coverage data (code 5013).

The stack trace is:
```
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:82)
	at com.mountainminds.eclemma.internal.core.MemoryExecutionDataSource.readFrom(MemoryExecutionDataSource.java:68)
	at com.mountainminds.eclemma.internal.core.launching.AgentServer.run(AgentServer.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```
The question is if something can be done to avoid this error from EclEmma's point of view. JaCoCo behaves correctly as it is shutting down as fast as possible and therefore not dumping any coverage information. Maybe this only needs to be documented somewhere.

I changed my unit test to always clear the interrupted status (even though this might cause an external interruption to be lost).

**Comment by marchof** [comment]
Root cause is within JDK: https://bugs.openjdk.java.net/browse/JDK-8154017
