### ISSUE TITLE
"Error while creating report" when using annotation on a generic local variable

### ISSUE THREAD

**Issue by DannyBirkefeld** [jacoco/eclemma#98]
We have some problems with jacoco at our projects. We use Java 8 (1.8.0_31) and the latest version (0.7.2.201409121644) of jacoco. 

After a lot of search and trying I simplified the error causing code to the following:

// interface
public interface IInterface<T> {
	void doIt(T t);
}

// implementation (Impl.class)
public class Impl<T extends CharSequence> implements IInterface<T> {
	@Override
	public void doIt(final T t) {
                // The error is caused by this annotation, but only if T extends something
		@Annotation
		int i = t.charAt(0);
		System.out.println(i);
	}
}

// annotation
@Target({ElementType.TYPE_USE})
@Documented
@Retention(RetentionPolicy.CLASS)
public @interface Annotation {
	// nothing
}

// junit test
@Test
public void testBar() {
	final Impl<String> f = new Impl<>();
	f.doIt("hello");
	Assert.assertTrue(true);
}

The error ouput is of this sample is:

Error while creating report
	at org.jacoco.ant.ReportTask.execute(ReportTask.java:500)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	... 15 more
Caused by: java.io.IOException: Error while analyzing class test\Impl.class.
	at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:150)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:144)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:175)
	at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:569)
	at org.jacoco.ant.ReportTask.createReport(ReportTask.java:547)
	at org.jacoco.ant.ReportTask.execute(ReportTask.java:494)
	... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
	at org.jacoco.asm.ClassReader.readLabel(ClassReader.java:2174)
	at org.jacoco.asm.ClassReader.readTypeAnnotations(ClassReader.java:1598)
	at org.jacoco.asm.ClassReader.readCode(ClassReader.java:1184)
	at org.jacoco.asm.ClassReader.readMethod(ClassReader.java:1017)
	at org.jacoco.asm.ClassReader.accept(ClassReader.java:693)
	at org.jacoco.asm.ClassReader.accept(ClassReader.java:506)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:107)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:142)
	... 33 more

**Comment by DannyBirkefeld** [comment]
I just saw that some Characters were removed, so again the code:

```
// interface
public interface IInterface<T> {
	void doIt(T t);
}

// implementation (Impl.class)
public class Impl<T extends CharSequence> implements IInterface<T> {
	@Override
	public void doIt(final T t) {
		@Annotation
		int i = t.hashCode();
		System.out.println(i);
	}
}

// annotation
@Target({ElementType.TYPE_USE})
@Documented
@Retention(RetentionPolicy.CLASS)
public @interface Annotation {
	// nothing
}

// unit test
public class ImplTest {
	@Test
	public void testBar() {
		final Impl<String> f = new Impl<>();
		f.doIt("hello");
		Assert.assertTrue(true);
	}
}
```

**Comment by marchof** [comment]
Hm, can't reproduce. Can you please provide the four class files?

**Comment by DannyBirkefeld** [comment]
Have you used the java 8 oracle compiler?

I have attached the class files. I hope this works with e-mail.

Von: Marc R. Hoffmann [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. Februar 2015 15:24
An: jacoco/eclemma
Cc: Birkefeld, Danny
Betreff: Re: [eclemma] "Error while creating report" when using annotation on a generic local variable (#98)


Hm, can't reproduce. Can you please provide the four class files?

**Comment by DannyBirkefeld** [comment]
It seems like I can't provide the class files via mail or directly to this issue.
One wthing I have to add, the error does not occur with the eclipse compiler.

**Comment by marchof** [comment]
@DannyBirkefeld Actuall I tried with Eclipse as the bug was opened against EclEmma.

**Comment by DannyBirkefeld** [comment]
Ok, then I have used the wrong issue tracker. I dind't know that there is a special one for jacoco.

**Comment by marchof** [comment]
No problem!

**Comment by marchof** [comment]
With JDK compiler I can reproduce. I'll have a look.

**Comment by Godin** [comment]
@marchof should we wait with release of 0.7.3 because of this issue?

**Comment by marchof** [comment]
@Godin Probably not something that we can fix soon. Looks more like a javac or ASM issue. I'll investigate.

**Comment by marchof** [comment]
Shit, seems to be a javac bug. Here is a detailed analysis. I'll report to OpenJDK/Oracle.

https://gist.github.com/marchof/070ee2c2077bd095ba96

**Comment by Godin** [comment]
@marchof :) and they already have tag "jacoco-found" - https://bugs.openjdk.java.net/issues/?jql=labels%20%3D%20jacoco-found

**Comment by marchof** [comment]
@Godin How cool is that ;-)

I just submitted a bug at http://bugreport.java.com/

**Comment by marchof** [comment]
@DannyBirkefeld So it looks like we can't provide a quick fix for this as the root cause is the Java compiler itself.
A possible workaround is to avoid type annotations in this method and e.g. delegate to another private method which contains the type annotations.

**Comment by DannyBirkefeld** [comment]
Ok, thanks. Do you have a bug number for the javac bug?

**Comment by marchof** [comment]
Not yet. Bug reporting at OpenJDK is a black hole :-(

**Comment by Godin** [comment]
@marchof for me usually it takes from 1 to 2 days

**Comment by Godin** [comment]
@marchof also IDs are persistent and transparent , so URL will be https://bugs.openjdk.java.net/browse/JI-9019173 when it will be processed and it is invisible since the beginning to avoid publication of security vulnerabilities

**Comment by marchof** [comment]
Here is the JDK bugreport: https://bugs.openjdk.java.net/browse/JDK-8073658
