### ISSUE TITLE
Eclipse coverrage with JMocked using assertions in mocked methodes

### ISSUE THREAD

**Issue by lordgit** [jacoco/eclemma#99]
Coverrage crashed after I use assertions in mocked methods 

new MockUp<MyMockedClass >() {

      @Mock(invocations = 1)
      void setSomeThing(String value) {
            assertEquals("myString", value);
      }
 }

**Comment by marchof** [comment]
What exactly do you mean by "crashed"? Any error message? Unexpected result?

**Comment by lordgit** [comment]
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at myTest.testSomeThing$9.<init>(testSomeThing.java:182)
	at myTest.testSomeThing(testSomeThing.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by marchof** [comment]
What mocking framework are you using? It is a know limitation that JaCoCo does not work well with mocking frameworks which modify the classes under test.

**Comment by lordgit** [comment]
I use jmocked 1.15
It's working,  but not with deeper assertions.  See my first comment.

**Comment by marchof** [comment]
As said before: replacing classes at runtime doesn't work with JaCoCo.
